development:
  adapter: postgresql
  database: greatblogdev
  username: postgres
  password: abcd1234
  host: localhost
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  database: greatblogtest
  username: postgres
  password: abcd1234
  host: localhost
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: greatblogprod
  username: postgres
  password: abcd1234
  host: localhost
  pool: 5
  timeout: 5000