development:
  adapter: postgresql
  database: greatblogdev
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  database: greatblogtest
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: greatblogprod
  pool: 5
  timeout: 5000